terraform {
  required_version = ">= 1.5.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.0"
    }
    random = {
      source  = "hashicorp/random"
      version = ">= 3.5"
    }
  }

  # bucket is injected at `terraform init` via prod-bucket.conf (generated by Makefile)
  backend "s3" {
    key    = "live/prod/terraform.tfstate"
    region = "us-east-1"
  }
}
