
    bucket         = "terraform-aws-admin-primary-<ca-account-id>"
    key            = "sso/terraform.tfstate"
    region         = "us-east-1"
    use_lockfile   = true
    #dynamodb_table = "terraform_lock"
    #primary key: LockID

